/* Generated by wayland-scanner — wl_drm protocol marshalling. */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface wl_buffer_interface;

static const struct wl_interface *drm_types[] = {
	NULL,
	&wl_buffer_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_buffer_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_buffer_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};

static const struct wl_message wl_drm_requests[] = {
	{ "authenticate", "u", drm_types + 0 },
	{ "create_buffer", "nuiiuu", drm_types + 1 },
	{ "create_planar_buffer", "nuiiuiiiiii", drm_types + 7 },
	{ "create_prime_buffer", "2nhiiuiiiiii", drm_types + 18 },
};

static const struct wl_message wl_drm_events[] = {
	{ "device", "s", drm_types + 0 },
	{ "format", "u", drm_types + 0 },
	{ "authenticated", "", drm_types + 0 },
	{ "capabilities", "u", drm_types + 0 },
};

const struct wl_interface wl_drm_interface = {
	"wl_drm", 2,
	4, wl_drm_requests,
	4, wl_drm_events,
};

/* Helper for C++ callers: avoids name collision between the wl_interface
   variable and the struct wl_drm_interface callback vtable type. */
const struct wl_interface* wl_drm_interface_ptr(void) {
	return &wl_drm_interface;
}
