/* Generated by wayland-scanner — wl_drm server protocol for Mesa EGL device discovery. */

#ifndef DRM_SERVER_PROTOCOL_H
#define DRM_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_buffer;
struct wl_drm;

extern const struct wl_interface wl_drm_interface;

enum wl_drm_error {
	WL_DRM_ERROR_AUTHENTICATE_FAIL = 0,
	WL_DRM_ERROR_INVALID_FORMAT = 1,
	WL_DRM_ERROR_INVALID_NAME = 2,
};

#ifndef WL_DRM_CAPABILITY_ENUM
#define WL_DRM_CAPABILITY_ENUM
enum wl_drm_capability {
	WL_DRM_CAPABILITY_PRIME = 1,
};
#endif

struct wl_drm_interface {
	void (*authenticate)(struct wl_client *client,
			     struct wl_resource *resource,
			     uint32_t id);
	void (*create_buffer)(struct wl_client *client,
			      struct wl_resource *resource,
			      uint32_t id,
			      uint32_t name,
			      int32_t width,
			      int32_t height,
			      uint32_t stride,
			      uint32_t format);
	void (*create_planar_buffer)(struct wl_client *client,
				     struct wl_resource *resource,
				     uint32_t id,
				     uint32_t name,
				     int32_t width,
				     int32_t height,
				     uint32_t format,
				     int32_t offset0,
				     int32_t stride0,
				     int32_t offset1,
				     int32_t stride1,
				     int32_t offset2,
				     int32_t stride2);
	void (*create_prime_buffer)(struct wl_client *client,
				    struct wl_resource *resource,
				    uint32_t id,
				    int32_t name,
				    int32_t width,
				    int32_t height,
				    uint32_t format,
				    int32_t offset0,
				    int32_t stride0,
				    int32_t offset1,
				    int32_t stride1,
				    int32_t offset2,
				    int32_t stride2);
};

#define WL_DRM_DEVICE 0
#define WL_DRM_FORMAT 1
#define WL_DRM_AUTHENTICATED 2
#define WL_DRM_CAPABILITIES 3

static inline void
wl_drm_send_device(struct wl_resource *resource_, const char *name)
{
	wl_resource_post_event(resource_, WL_DRM_DEVICE, name);
}

static inline void
wl_drm_send_format(struct wl_resource *resource_, uint32_t format)
{
	wl_resource_post_event(resource_, WL_DRM_FORMAT, format);
}

static inline void
wl_drm_send_authenticated(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, WL_DRM_AUTHENTICATED);
}

static inline void
wl_drm_send_capabilities(struct wl_resource *resource_, uint32_t value)
{
	wl_resource_post_event(resource_, WL_DRM_CAPABILITIES, value);
}

#ifdef  __cplusplus
}
#endif

#endif
